server:
  port: 8081

spring:
  profiles:
    active: mysql  # Change to h2 for testing, mysql for production

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    hibernate:
      ddl-auto: update
      cache:
        use_second_level_cache: false



  
