spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rugbyblog_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root  # change if necessary

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create    
    show-sql: true    
